# Test the Pharm2D fingerprint scoring component

run_type = "scoring"
output_csv = "pharm2dfp.csv"
json_out_config = "_pharm2dfp.json"

[parameters]

smiles_file = "tests/chembl_random_1000.smi"


[scoring]

type = "geometric_mean"
parallel = false

[[scoring.component]]
[scoring.component.Pharm2DFP]

[[scoring.component.Pharm2DFP.endpoint]]
name = "Pharm2DFP"

params.ref_smiles = "CC(=O)OC1=CC=CC=C1C(=O)O"  # Aspirin
params.type = "base"
params.bins = [0, 2, 2, 4, 4, 8]  # mean [(0,2), (2,4), (4,8)]
params.min_point_count = 2
params.max_point_count = 3
params.similarity = "tanimoto"
