run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_RL"
json_out_config = "_RL.json"

[parameters]

use_checkpoint = false

prior_file = "reinvent.prior"  # change as needed
agent_file = "reinvent.prior"  # same here
summary_csv_prefix = "RL"

batch_size = 100
randomize_smiles = true


[learning_strategy]

type = "dap"
sigma = 128
rate = 0.0001


[diversity_filter]

type = "IdenticalMurckoScaffold"
bucket_size = 10
minscore = 0.7
minsimilarity = 0.5


[inception]

memory_size = 50
sample_size = 10


[[stage]]
termination = "simple"
max_score = 1.0
max_steps = 200

chkpt_file = 'RL.chkpt'

[stage.scoring]
type = "geometric_mean"


[[stage.scoring.component]]
[stage.scoring.component.QED]

[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 1.0
